name: Benchmarks

on:
    push:
    workflow_dispatch:

permissions:
    contents: read

jobs:
    time:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: astral-sh/setup-uv@v5
              with:
                  enable-cache: true
            - run: uv sync --all-extras --dev
            - run: uv run bench.py -o time.json --stats --fast
            - uses: actions/upload-artifact@v4
              with:
                  name: Results
                  path: ./*.json
            - run: uv cache prune --ci
    memory:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: astral-sh/setup-uv@v5
              with:
                  enable-cache: true
            - run: uv sync --all-extras --dev
            - run: uv run bench.py -o memory.json --stats --tracemalloc --fast
            - uses: actions/upload-artifact@v4
              with:
                  name: Results
                  path: ./*.json
            - run: uv cache prune --ci
    quality:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: astral-sh/setup-uv@v5
              with:
                  enable-cache: true
            - run: uv sync --all-extras --dev
            - run: uv run quality.py
            - uses: actions/upload-artifact@v4
              with:
                  name: Results
                  path: ./*.json
            - run: uv cache prune --ci
