name: Benchmarks

on:
  push:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  benchmark:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
      - run: uv sync --all-extras --dev
      - run: uv run main.py -o time.json --dump --stats
      - run: uv run main.py -o memory.json --dump --stats --tracemalloc
      - run: uv run pyperf stats time.json
      - run: uv run pyperf stats memory.json
      - uses: actions/upload-artifact@v4
        with:
          name: Results
          path: |
            time.json
            memory.json
      - run: uv cache prune --ci
